import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./Components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ANKIT GAME HUB",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main>{children}</main>

        <Footer></Footer>
      </body>
    </html>
  );
}
